name: 'assay.it webhook'
description: 'the action triggers quality assessment at assay.it'
inputs:
  secret:
    description: 'secret token to access assay.it'
    required: true
  target:
    description: 'url or other identity of target system to execute a quality assurance'
    required: false
  api:
    description:
    required: false
    default: 'api.assay.it'
runs:
  using: 'docker'
  image: 'Dockerfile'
