name: 'assay.it webhook'
description: 'the action triggers quality assessment at assay.it'
input:
  secret:
    description: 'secret token to access assay.it'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secret }}
