name: 'assay-it'
description: 'Test Cloud Apps in Production. Confirm Quality & Eliminate Risk with https://assay.it'
inputs:
  version:
    description: |
      The version of assay-it to use.
    required: true
    default: "v1.0.6"
  install-go:
    description: |
      Golang is required for running assay-it. 
      If set to false, the action expects you to have installed Go already.
    required: true
    default: true
  working-directory:
    description: |
      Path to the working directory assay-it should be executed in.
      If skipped, the action uses $GITHUB_WORKSPACE.
      This is useful when dealing with multiple projects within one repository.
    required: false
    default: ""
  system-under-test:
    description: |
      Url of target system to execute a quality checks.
      It shall start with protocol scheme (e.g. https://assay.it) 
    required: true
  verbose:
    description: |
      Verbose output of unit tests
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - id: install_go
      if: ${{ inputs.install-go != 'false' }}
      uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: "1.20.x"
    - env:
        version: ${{ inputs.version }}
        sut: ${{ inputs.system-under-test }}
        verbose: ${{ inputs.verbose }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        curl -L -o assay-it.tag.gz https://github.com/assay-it/assay-it/releases/download/${version}/assay-it_Linux_x86_64.tar.gz
        tar -xvf assay-it.tag.gz
        mv assay-it $(go env GOPATH)/bin/assay-it
        rm assay-it.tag.gz

        opts=(
          --sut ${sut}
        )
        if [[ "${verbose}" == "true" ]]; then
          opts+=(-v)
        fi
        $(go env GOPATH)/bin/assay-it test "${opts[@]}"
      shell: bash
