name: 'assay.it webhook'
description: 'the action triggers quality assessment at assay.it'
input:
  secret:
    description: 'secret token to access assay.it'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secret }}
    - ${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/${{ github.event.pull_request.head.sha }}
    - ${{ github.event.pull_request.base.repo.full_name }}/${{ github.event.pull_request.base.ref }}/${{ github.event.pull_request.base.sha }}
    - ${{ github.event.number }}
    - "${{ github.event.pull_request.title }}"
