name: 'assay.it webhook'
description: 'the action triggers quality assessment at assay.it'
input:
  secret:
    description: 'secret token to access assay.it'
    required: true
  api:
    description: 'api endpoint of assay.it'
    required: true
    default: 'latest.assay.it'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api }}
    - ${{ inputs.secret }}
